FROM futureys/claude-code-python-development:20251026170000
# build-essential (make): Since project uses shell script with shebang #!/bin/bash
RUN apt-get upgrade \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
        build-essential/stable \
 && apt-get -y autoremove \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
COPY pyproject.toml README.rst /workspace/
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --python 3.13
COPY . /workspace/
CMD ["make", "tests"]
